package app.database;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Represents a player from the database
 * 
 * @author Rubén Jiménez Goñi
 */
@Entity
public class DBPlayer {

	/**
	 * Id of the player
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	/**
	 * Name of the player
	 */
	@Column(unique = true)
	private String name;

	/**
	 * Score of the player
	 */
	private long score;

	/**
	 * For JPA use
	 */
	protected DBPlayer() {
	}

	/**
	 * Constructor that receives the player's name and score
	 * 
	 * @param name
	 *            Name of the player
	 * @param score
	 *            Score of the player
	 */
	public DBPlayer(String name, long score) {
		this.name = name;
		this.score = score;
	}

	/**
	 * Returns the player's id which is autogenerated.
	 * 
	 * @return Player's id
	 */
	public long getId() {
		return id;
	}

	/**
	 * Returns the player's name
	 * 
	 * @return Player's name
	 */
	public String getName() {
		return name;
	}

	/**
	 * Returns the player's score
	 * @return Player's score
	 */
	public long getScore() {
		return score;
	}

	/**
	 * Allow to increase the player's score
	 * 
	 * @param toAdd Score to add to the current score of the player
	 */
	public void increaseScore(long toAdd) {
		score += toAdd;
	}

}
